---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  interval: 1m0s
  values:
    # devices:
    #   - wg0
    nodePort:
      enabled: true
    encryption:
      enabled: false
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true
    kubeProxyReplacement: true
    operator:
      replicas: 1
    socketLB:
      hostNamespaceOnly: true
    k8sServiceHost: 172.20.0.0.2
    k8sServicePort: 6443
