---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  interval: 1m0s
  values:
    egressGateway: 
      enabled: true
    bpf:
      masquerade: false
    enableIPv4Masquerade: true
    ipv4NativeRoutingCIDR: 10.0.0.0/24
    k8sServiceHost: 155.246.36.10
    k8sServicePort: 6443
    kubeProxyReplacement: true
    nodePort:
      enabled: true
    operator:
      replicas: 1
    routingMode: native
    socketLB:
      hostNamespaceOnly: true
