apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: kube-system
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
        - name: perms
          image: busybox:latest
          volumeMounts:
            - mountPath: "/downloads"
              name: downloads
          command:
            - sh
            - -c
            - |
              mkdir -p /downloads
              chown -R 1000:1000 /downloads
              chmod -R u+rwX,g+rwX /downloads
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/downloads"
              name: downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          ports: 
            - containerPort: 8080
            - containerPort: 6881
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          persistentVolumeClaim:
            claimName: jellyfin-media
