---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr-route
  namespace: kube-system
spec:
  parentRefs:
    - name: traefik
      sectionName: web-internal-gw
  hostnames:
    - radarr.internal
  rules:
    - backendRefs:
      - name: radarr
        port: 7878
