---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: kube-system
spec:
  chart:
    spec:
      chart: minecraft
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
      version: '>=5.1.3'
  interval: 10m0s
  values:
    resources:
      requests:
        memory: "8G"
        cpu: 2
      limits:
        memory: "10G"
        cpu: 3
    image:
      repository: itzg/minecraft-server
      tag: stable-java21
      pullPolicy: Always
    persistence:
      dataDir:
        enabled: true
        Size: 50Gi
    minecraftServer:
      eula: "TRUE"
      motd: "hi"
      difficulty: normal
      type: "AUTO_CURSEFORGE"
      version: "1.21.1"
      cfServerMod: "/data/atm-server.zip"
      autoCurseforge:
        apiKey:
          existingSecret: curseforge-api-key
          secretKey: curseforge-api-key
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/craftoria"
        # include:
        #   - "create-aeronautics"
