---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: kube-system
spec:
  chart:
    spec:
      chart: minecraft
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
      version: '>=5.1.3'
  interval: 10m0s
  values:
    livenessProbe:
      initialDelaySeconds: 900
      periodSeconds: 10
      failureThreshold: 30

    readinessProbe:
      initialDelaySeconds: 900
      periodSeconds: 10
      failureThreshold: 30
    image:
      repository: itzg/minecraft-server
      tag: stable-java21
      pullPolicy: Always
    persistence:
      dataDir:
        enabled: true
        Size: 50Gi
    minecraftServer:
      memory: 10G
      eula: "TRUE"
      motd: "hi"
      difficulty: normal
      type: "CURSEFORGE"
      version: "1.21.1"
      cfServerMod: "/data/atm-server.zip"
