apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: kube-system
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/downloads"
              name: downloads
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_HTML
              value: "false"
            - name: TZ
              value: "Etc/UTC"
          ports: 
            - containerPort: 8191
