apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: kube-system
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      initContainers:
        - name: perms
          image: busybox:latest
          volumeMounts:
            - mountPath: "/media"
              name: media
          command:
            - sh
            - -c
            - |
              mkdir -p /media/film
              chown -R 1000:1000 /media/film
              chmod -R u+rwX,g+rwX /media/film
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/media"
              name: media
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          ports: 
            - containerPort: 7878
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-media
